#!/bin/bash

if [ $# == 1 ]; then
	KUBECONFIG_FOLDER=$1
	echo " Using path: $KUBECONFIG_FOLDER"
	kubectl create -f $KUBECONFIG_FOLDER/storage-class-gce-slow.yaml
	kubectl create -f $KUBECONFIG_FOLDER/storage-class-gce-fast.yaml
	kubectl create -f $KUBECONFIG_FOLDER/nfs-server-pvc.yaml
	kubectl create -f $KUBECONFIG_FOLDER/nfs-server-rc.yaml
	kubectl create -f $KUBECONFIG_FOLDER/nfs-server-service.yaml

	# You will need the ClusterIP of the nfs-server service
	kubectl describe services nfs-server
else
	echo " Invalid arguments: ./$0 NFS_KUBECONFIG_FOLDER"
fi
